### ISSUE TITLE
Toot の Content のパースの共通化

### ISSUE THREAD

**Issue by amay077** [kmycode/mastoom#3]
ちょっと再実装になってしまったけど、 https://github.com/kmycode/mastoom/pull/2 の

https://github.com/kmycode/mastoom/pull/2/files#diff-c48148810a3cd420add9f2f4a9c47b9f

の ``StatusParser`` というクラスで HTML で返される Toot の Content をパースして、 ``TootSpan`` のリストに変換しています。

これは [SgmlReader for Portable Class Library](https://www.nuget.org/packages/CenterCLR.SgmlReader/) というライブラリを使っています。

master の方では Html Agility Pack を使われているようなので、それでも良いと思いますが、パース結果を ``TootSpan`` のようにモデル化してもらえると、プラットフォーム関係なく使えるので、そうしてもらえるとありがたいです。

``StatusParser`` のパース実装は mastodon のドキュメントなどを一切見ずに実装したので、間違ってるところがあるかもしれません（が、数時間 Federeted Timeline を流して、エラーになるものはなかったみたいです）。

**Comment by kmycode** [comment]
ざくっと調べてみましたが、
http://atsushieno.hatenablog.com/entry/2013/09/06/053327
こちらの記事によりますと、Html Agility Packには終了タグのないタグがうまく変換できない問題があるみたいですね。

オリジナルのMastodonではないかもしれませんが、これからインスタンス増える中で
インスタンスの改造によってこの問題が出てくる可能性ありますね。

HTMLパースのロジックとしてすでに整形されているし、記述も簡潔そうなのでこの部分はあめいさんのコードに追従したいですが・・・
SgmlReaderクラスとかそれっぽい名前空間が見当たりませんが、拡張メソッドとして実装されているのでしょうか？

**Comment by amay077** [comment]
なんと実は SgmlReader が使われてませんでしたーすいませんー。

https://github.com/kmycode/mastoom/pull/2/commits/65807a79e860327dc9b1ca735442734e47d2e873

で直しました。

こちらを使ってもらえるなら、好きなように .Shared に移動してもらって、名前空間やクラス名も変更してもらって構いませんのでよろしくですー。

**Comment by kmycode** [comment]
／￣ヽ―、
　彡　　　　＞―-､＿
　/ /|||ヽ彡　　　　ヽ
　ﾚｲ_从ヾ_/ /|||ヽ　 |
（|ﾏo| ｨoﾌﾚｲ_从ヾ_＼ |
　|u〈　 (|fo)イoヽ 6)
　ヽヽ二) |uヽ　￣u ∧
　 /＼＿／ヽヽ二)　/ /
　｜ヽ)＿／/＼＿_／／
　/　　　 /　|＞-＜＿
＿人人人人人人人人＿
＞ な　なんだって ＜
＞ ━━━━━━!! ＜
￣ＹＹＹＹＹＹＹＹ￣
　／￣￣￣ヾ⌒)
`/　／￣`ー-＜
｜ /　u　　 |｜
｜Y　＼＿ﾉ､_Ｖ
(6　〈oヽ (o｜
∧　u ￣　/~/
| ヽ　(二> /
ヽ　＼_＿／＼
　＼へ_/へ| ∧

おけです！ありがとうございます！
